version: 2.1.{build}
image: Visual Studio 2019
environment:
  PYTHON: C:\Python38-x64
install:
- cmd: '"%PYTHON%\python.exe" -m pip install requirements.txt '
- cmd: '"%PYTHON%\python.exe" -m pip install pyinstaller scipy '
build_script:
- cmd: '"%PYTHON%\Scripts\pyinstaller" --onefile qenc.py --icon=app.ico'
test: off
artifacts:
- path: dist/qenc.exe
